# Generated by Django 5.2.7 on 2026-02-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouncie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouncietoken',
            name='user',
        ),
        migrations.AddField(
            model_name='bouncietoken',
            name='authorization_code',
            field=models.TextField(default=''),
        ),
    ]
