# Generated by Django 5.2.7 on 2026-02-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouncie', '0002_remove_bouncietoken_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('tripData', 'Trip Data'), ('tripStart', 'Trip Start'), ('tripEnd', 'Trip End'), ('tripMetrics', 'Trip Metrics'), ('deviceConnect', 'Device Connect'), ('deviceDisconnect', 'Device Disconnect'), ('battery', 'Battery'), ('mil', 'MIL'), ('vinChange', 'VIN Change'), ('applicationGeoZone', 'Application Geo-Zone'), ('userGeoZone', 'User Geo-Zone')], db_index=True, max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Vehicle Event',
                'verbose_name_plural': 'Vehicle Events',
                'ordering': ['-received_at'],
            },
        ),
    ]
