# Generated by Django 5.2.7 on 2025-12-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("truck_number_plate", models.CharField(max_length=3000, unique=True)),
                ("truck_size", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "truck_capacity",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "driver_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("inspection_date", models.DateField(blank=True, null=True)),
                (
                    "insurance_details",
                    models.FileField(
                        blank=True, null=True, upload_to="./media/insurance_docs/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
