# Generated by Django 5.2.7 on 2025-12-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("truck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="truck_type",
            field=models.CharField(
                blank=True,
                choices=[("normal", "Normal"), ("box", "Box")],
                default="box",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="truck",
            name="truck_number_plate",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
