# Generated by Django 5.2.7 on 2026-01-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_truck_truck_type_alter_truck_truck_number_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_size', models.CharField(max_length=150)),
                ('minimum_distance', models.FloatField(help_text='Minimum distance (in KM) covered by minimum charge')),
                ('minimum_charge', models.FloatField(help_text='Base charge for minimum distance')),
                ('unite_price', models.FloatField(help_text='Charge per extra KM after minimum distance')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
