# Generated by Django 5.2.7 on 2026-02-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_pricemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoversManagements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movers_number', models.PositiveIntegerField()),
                ('hour_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
