# Generated by Django 5.2.7 on 2026-02-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0004_moversmanagements'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='imei',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='live_fuel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='live_heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='live_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='live_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='live_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['imei'], name='truck_truck_imei_0b5218_idx'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['status'], name='truck_truck_status_e679f9_idx'),
        ),
    ]
