# Generated by Django 5.2.7 on 2026-02-06 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('truck', '0004_moversmanagements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_track', models.JSONField(blank=True, help_text='Price snapshot at booking time', null=True)),
                ('movers', models.JSONField(blank=True, help_text='Movers snapshot at booking time', null=True)),
                ('pickup_time', models.DateTimeField()),
                ('pickup_address', models.TextField()),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_off_address', models.TextField()),
                ('drop_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('movable_items', models.JSONField(blank=True, null=True)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('start', 'Start'), ('complete', 'Complete'), ('reject', 'Reject')], default='pending', max_length=20)),
                ('truck_payment_status', models.BooleanField(default=False)),
                ('mover_payment_status', models.BooleanField(default=False)),
                ('overview_polyline', models.TextField(blank=True, help_text='Encoded polyline from Google Directions API', null=True)),
                ('distance_meter', models.PositiveIntegerField(blank=True, help_text='Total distance in meters', null=True)),
                ('duration_second', models.PositiveIntegerField(blank=True, help_text='Total duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='truck.truck')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
