# Generated by Django 5.2.7 on 2026-02-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_end_time_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Admin internal note', null=True),
        ),
    ]
