# Generated by Django 5.2.7 on 2026-02-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_admin_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='movable_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
