# Generated by Django 5.2.7 on 2026-02-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_movable_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('start', 'Start'), ('end_request', 'End Request'), ('end', 'End'), ('complete', 'Complete'), ('reject', 'Reject')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreements', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='booking.booking')),
            ],
        ),
    ]
