# Generated by Django 5.2.7 on 2026-02-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_status_bookingagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drop_elevator_stair',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_elevator_stair',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
