# Generated by Django 5.2.7 on 2026-02-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin_notification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_notification',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
