# Generated by Django 5.2.7 on 2026-02-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_admin_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_notification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
